version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: ./todo-app
    working_dir: /app
    volumes:
      - ./todo-app:/app:Z
    environment:
      DATABASE_URL: postgres://todo:todo@db:5432/todo
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata:
